# Generated by Django 5.1.6 on 2026-03-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('CLINIC_ADMIN', 'Clinic Admin'), ('DOCTOR', 'Doctor'), ('RECEPTIONIST', 'Receptionist'), ('PATIENT', 'Patient')], default='SUPER_ADMIN', max_length=20),
        ),
    ]
